config/routes.rb
Rails.application.routes.draw do
  get '/' => "pages#index", as: "pages"
  get '/contact' => "pages#contact"
  get '/portfolio' => "pages#portfolio"
  get '/about' => "pages#about"

  resources :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :name, presence: true

  validate :has_a_contact

  def has_a_contact
    unless [phone?, email?].include?(true)
      errors.add :base, 'Please provide at least one way for us to contact you!'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def contact
  end

  def gallery
  end

  def about
  end
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    binding.pry
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

  def request_params
    params.require("request").permit(:name, :phone, :email, :address, :square_footage, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ValgreenPainting</title>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lobster+Two:400,400italic|Oswald:400,300,700' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-fixed-top navbar-default" id="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag 'valgreen', id:"logo" %></a>
      <a class="navbar-brand" href="/"><%= image_tag 'valgreen2', id:"logo2" %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a class="<%= 'active' if current_page?(portfolio_path) %>" href="/portfolio">Portfolio</a></li>
        <li><a class="<%= 'active' if current_page?(about_path) %>" href="/about">About</a></li>
        <li><a class="<%= 'active' if current_page?(new_request_path) %>" href="/requests/new">Request</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid site-wrapper">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div id="portfolio-bg" class="background"></div>

<div class="info-card">
  <h3 class="center">ABOUT US</h3>
  <hr>
  <p>Hodor hodor hodor Hodor hodor HODOR. Hodor hodor HODOR hodor hodor hodor Hodor. Hodor hodor hodor Hodor HODOR hodor hodor hodor. Hodor hodor hodor HODOR hodor Hodor hodor. Hodor hodor Hodor hodor hodor hodor HODOR hodor. Hodor HODOR hodor Hodor hodor hodor hodor hodor. Hodor Hodor hodor hodor hodor hodor HODOR. Hodor HODOR hodor hodor hodor hodor hodor Hodor.</p>
  <p>Hodor hodor hodor hodor Hodor hodor. Hodor hodor hodor hodor Hodor HODOR hodor hodor. Hodor hodor hodor hodor hodor hodor HODOR hodor. Hodor Hodor hodor hodor HODOR hodor. Hodor hodor hodor hodor Hodor hodor hodor HODOR.</p>
  <p>Hodor hodor hodor Hodor hodor HODOR. HODOR hodor hodor hodor hodor hodor Hodor hodor. Hodor hodor Hodor HODOR hodor hodor hodor hodor. Hodor HODOR hodor hodor Hodor hodor hodor hodor. Hodor hodor hodor Hodor hodor HODOR. HODOR hodor hodor hodor hodor hodor Hodor hodor. Hodor HODOR hodor hodor hodor hodor hodor hodor.</p>
</div>

<script type="text/javascript">
  $("#logo").hide();
  $("#logo2").show();
</script>

app/views/pages/index.html.erb
<div id="splash-image-desat" class="background"></div>
<div id="splash-image-sat" class="background"></div>
<div class="header">
  <div class="header-title">VALGREEN PAINTING</div>
  <div class="header-tag">painting your stuff since 1984</div>
</div>
<div class="splash-buttons">
  <%= link_to 'Request a Job', contact_path, class:"btn btn-primary" %>
</div>
<div id="request">

</div>

<script type="text/javascript">
  $(function() {
    $("#splash-image-desat").delay(1000).fadeOut(7000);
    $("#splash-image-sat").delay(1000).fadeIn(7000);
  })
</script>

app/views/pages/portfolio.html.erb
<div id="portfolio-bg" class="background"></div>

<div class="portfolio-gallery">
  <%= image_tag 'hous1-compressor' %>
  <%= image_tag 'hous2-compressor' %>
  <%= image_tag 'hous3' %>
  <%= image_tag 'hous4-compressor' %>
  <%= image_tag 'hous5' %>
  <%= image_tag 'hous6' %>
</div>
<div class="arrows">

</div>

<script type="text/javascript">
  $(".portfolio-gallery").slick({
    speed: 300,
    infinite: true,
    slidesToShow: 3,
    slidesToScroll: 1,
    nextArrow:'<a class="btn btn-arrows">></a>',
    prevArrow:'<a class="btn btn-arrows"><</a>',
    appendArrows: $(".arrows"),
    responsive: [
      {
        breakpoint: 900,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1
        }
      },
      {
        breakpoint: 600,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1
        }
      },
    ]
  });
</script>

<script type="text/javascript">
  $("#logo").hide();
  $("#logo2").show();
</script>

app/views/requests/_form.html.erb
<div id="new-request-form">
  <%= form_for @request do |f| %>
    <h3 class="center">NEW REQUEST</h3>
    <div class="input-field col-md-12">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="input-field col-md-6">
      <%= f.label :phone %>
      <%= f.text_field :phone, class: "form-control" %>
    </div>
    <div class="input-field col-md-6">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="input-field col-md-6">
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="input-field col-md-6">
      <%= f.label :square_footage %>
      <%= f.text_field :square_footage, class: "form-control" %>
    </div>
    <div class="input-field col-md-12">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="submit-btn-wrapper">
      <%= f.submit "Submit Request", class: "btn btn-form" %>
    </div>
  <% end %>
</div>

app/views/requests/new.html.erb
<div id="portfolio-bg" class="background"></div>
<div class="info-card">
  <%= render 'form' %>
</div>

<script type="text/javascript">
  $("#logo").hide();
  $("#logo2").show();
</script>